
FROM pietrocolombi/test:latest

# Create app directory
WORKDIR /usr/src/app
RUN npm config set proxy http://gs02437:corsico8@10.209.4.37:8080

RUN npm config set https-proxy http://gs02437:corsico8@10.209.4.37:8080

EXPOSE 8080

